version: '3.4'

services:
  annotatortool:
    container_name: annotatortool
    image: annotatortool
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7500:7500
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo:latest 
    ports:
      - "27017:27017"
